language: haskell

services:
  - docker

before_install:
  - docker build -t matthinc/gpxoptim_ci .

script:
  - docker run --rm -it matthinc/gpxoptim_ci stack build
  - docker run --rm -it matthinc/gpxoptim_ci stack test
